[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ecg2dcm"
version = "1.2.0"
description = "Convert GE MUSE XML electrocardiogram files to DICOM 12-Lead ECG Waveform Storage"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name = "Seoul National University Hospital" }]
maintainers = [{ name = "Hyung-Chul Lee", email = "vital@snu.ac.kr" }]
keywords = ["ECG", "DICOM", "GE MUSE", "electrocardiogram", "waveform", "interoperability"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
dependencies = ["pydicom==2.4.4", "numpy", "tqdm"]

[project.urls]
Homepage = "https://github.com/HyeonhoonLee/ecg2dcm"
Repository = "https://github.com/HyeonhoonLee/ecg2dcm"
Issues = "https://github.com/HyeonhoonLee/ecg2dcm/issues"

[project.scripts]
ecg2dcm = "ecg2dcm.main:main"

[tool.hatch.build.targets.wheel]
packages = ["ecg2dcm"]
